#!/usr/bin/env python3
import sys
import os
from PySide6.QtWidgets import QApplication

LIB_DIR = "/usr/lib/disk-analyser"
if os.path.exists(LIB_DIR):
    sys.path.append(LIB_DIR)

try:
    from mainwindow import MainWindow
except Exception as e:
    print(f"Ошибка: {e}", file=sys.stderr)
    sys.exit(1)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
